name: the_sociopath_project
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^5.0.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  cloud_firestore_web: ^0.1.1+2
  firebase_auth_web: ^0.1.3+1
  firebase_core_web: ^0.1.1+2
  flutter_gifimage: ^1.0.1
  social_signin_buttons: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/loading_animation.gif
    - assets/images/logo.png
