/// Generated by AssetsRefGenerator on 2020/07/19
class Res {
  static const String loading_animation = "assets/images/loading_animation.gif";
  static const String logo = "assets/images/logo.png";
}
